name: CellSeg
channels:
- conda-forge

dependencies:
- pip
- python>=3.6
- pip:
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pytables
  - jupyter
  - notebook
  - quantities
  - ipywidgets
  - pythreejs
  - ipyvolume
  - vispy
  - meshio
  - zarr
  - xarray
  - vtk
  - tifffile
  - skimage
  - scipy
  - re
  - os
  - sparse
  - networkx